services:

  postgres:
    image: postgres:16
    container_name: moviehub-postgres
    restart: always
    environment:
      POSTGRES_DB: moviehub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: moviehub-keycloak
    command: start-dev
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  postgres_data:
