services:

  postgres:
    image: postgres:16
    container_name: moviehub-postgres
    restart: always
    environment:
      POSTGRES_DB: moviehub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: moviehub-keycloak
    command: start-dev
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  api:
    build: ./api
    container_name: moviehub-api
    restart: always
    depends_on:
      - postgres
      - keycloak
    ports:
     - "3000:3000"

  spa:
    build: ./spa
    container_name: moviehub-spa
    restart: always
    depends_on:
      - api
    ports:
      - "5173:5173"

  ssr:
    build: ./ssr
    container_name: moviehub-ssr
    restart: always
    depends_on:
      - api
    ports:
      - "3001:3001"


volumes:
  postgres_data:
  keycloak_data: